### ISSUE TITLE
Render function instead of component tag

### ISSUE THREAD

**Issue by JaySunSyn** [dedego/web-component-router#1]
Hi there, thanks for this router.

I was wondering if it would make sense to have a `render` function instead of a component tag name in the router.  Eventually, accepting both, `render` and `component` in the config.

Advantages:

- passing properties into the component would get easy
- rendering non-custom elements (+content) within a route would get possible. Something like `/404` =>  ```html<h2>404 The requested page could not be found</h2>```

```javascript
// eventually, not a *static* route getter

{
    path: "/stock/:type/:day",
    render: () => html`<page-stocks title="${this.stockTitle}"></page-stocks>`,
    import: () => import("./src/page_stock.js")
}
```

The question will arise how to pass on the `routeContext` to the rendered elements. We could either set it in every component rendered in the path or specify the component(s) in the config. I can imagine also scenarios like the following where components get combined:

```javascript
{
    path: "/stock/:type/:day",
    render: () => html`
        <h2>Stocks</h2>
        <page-stocks stock-id="12"></page-stocks>
        <page-stocks stock-id="14" @price-update=${this.sell}></page-stocks>
    `,
    import: () => import("./src/page_stock.js")
}
```

Would love to hear your opinion and if you'd accept PRs or if you think that the current way is the way to go.

Thanks

**Comment by dedego** [comment]
Hi JaySunSyn,

As of version 2.1.0 (which you helped me create), the render method is available.

Thanks for your suggestion.

**Comment by JaySunSyn** [comment]
Awesome, thanks a lot!
